name: cybathlon
channels:
    - conda-forge
dependencies:
  - python=3.7
  - pip
  - git
  - numpy
  - pandas
  - matplotlib
  - h5py
  - scikit-learn==0.22.1
  - pyserial
  - bokeh==2.0.2
  - pyqtgraph==0.11.*
  - tensorflow==2.1.0
  - scikit-optimize==0.7.4
  - keras-tuner==1.0.1
  - pip:
    - mne==0.18
    - pylsl==1.13.1
    - tensorflow-addons